<?php
$shipment = $this->getShipment();
$shipmentLines = $shipment["Lines"];
?>

<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper"><?= __('Shipment #') ?> <?= $shipment["No."] ?> </span>
    </h1>
    <div class="order-date">
        <span class="label"><?= __('Shipment Date:') ?></span>
        <date><?= date_format(date_create($shipment["Shipment Date"]), "d-m-Y") ?></date>
    </div>
</div>

<div class="actions-toolbar order-actions-toolbar">
    <div class="actions">
        <a href="<?= $shipment["PDFUrl"] ?>" class="action order" target="_blank">
            <span><?= __('Download PDF') ?></span>
        </a>
    </div>
</div>

<ul class="items order-links">
    <li class="nav item current"><strong><?= __('Items Shipped') ?></strong></li>
</ul>
<div class="order-details-items ordered">

    <div class="order-title">
        <strong><?= __('Items Shipped') ?></strong>
    </div>

    <div class="table-wrapper order-items">
        <table class="data table table-order-items" id="my-orders-table">
            <caption class="table-caption"><?= __('Items Shipped') ?></caption>
            <thead>
                <tr>
                    <th class="col name"><?= __('Product Name') ?></th>
                    <th class="col sku"><?= __('SKU') ?></th>
                    <th class="col qty"><?= __('Qty') ?></th>
                </tr>
            </thead>

            <?php foreach ($shipmentLines as $shipmentLine): ?>
            <?php
                    $itemNo = '';
                    if ((int)$shipmentLine["Type"] === 2) {
                        $itemNo = $shipmentLine["No."];
                    }
                ?>

            <tbody>
                <tr id="order-item-row-1">
                    <td class="col name" data-th="Product Name">
                        <strong class="product name product-item-name"><?= $shipmentLine["Description"]?></strong>
                    </td>
                    <td class="col sku" data-th="SKU"><?= $itemNo ?></td>
                    <td class="col qty" data-th="Qty">
                        <ul class="items-qty">
                            <li class="item">
                                <span class="content"><?= $shipmentLine["Quantity"] ?></span>
                            </li>
                        </ul>
                    </td>
                </tr>
            </tbody>
            <?php endforeach; ?>
        </table>
    </div>


    <div class="actions-toolbar">
        <div class="secondary">
            <a class="action back" href="/shipments/shipmentlist/">
                <span><?= __('Back to My Shipments') ?></span>
            </a>
        </div>
    </div>
</div>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= __('Shipment Information') ?></strong>
    </div>
    <div class="block-content">
        <div class="box box-order-shipping-address">
            <strong class="box-title"><span><?= __('Shipping Address') ?></span></strong>
            <div class="box-content">
                <address><?= $shipment["Ship-to Name"] ?><br />
                    <?= $shipment["Ship-to Address"] ?><br />
                    <?= $shipment["Ship-to City"] ?>, <?= $shipment["Ship-to Post Code"] ?><br />
                    <?= $shipment["Ship-to Country/Region Code"] ?><br />
                </address>
            </div>
        </div>
        <div class="box box-order-shipping-method">
            <strong class="box-title">
                <span><?= __('Shipping Method') ?></span>
            </strong>
            <div class="box-content">
                <div><?= $shipment["Shipment Method Code"] ?></div>
            </div>
        </div>
        <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?= __('Billing Address') ?></span>
            </strong>
            <div class="box-content">
                <address><?= $shipment["Bill-to Name"] ?><br />
                    <?= $shipment["Bill-to Address"] ?><br />
                    <?= $shipment["Bill-to City"] ?>, <?= $shipment["Bill-to Post Code"] ?><br />
                    <?= $shipment["Bill-to Country/Region Code"] ?><br />
                </address>
            </div>
        </div>
        <div class="box box-order-billing-method">
            <strong class="box-title">
                <span><?= __('Payment Method') ?></span>
            </strong>
            <div class="box-content">
                <dl class="payment-method checkmemo">
                    <?= $shipment["Payment Method Code"] ?>
                </dl>
            </div>
        </div>
    </div>
</div>
