<?php
/** @var \Commerce365\Shipments\Block\ShipmentList  $block */
$totalResults = 0;
$shipments = [];

$shipmentsResponse = $this->getShipments();
if (!empty($shipmentsResponse)) {
    $shipments = $shipmentsResponse["salesDocuments"];
    $totalResults = $shipmentsResponse["totalResults"];
}
?>

<div class="table-wrapper orders-history">
<?php if (count($shipments) > 0): ?>
    <form action="<?= $this->getFilterActionUrl() ?>" method="get">
        <div class="search-form-fields">
            <input type="text" placeholder="<?= __('Search...') ?>" name="searchString"/>
            <button type="submit" title="<?= __('Search') ?>" class="action primary">
                <span><?= __('Search') ?></span>
            </button>
        </div>
    </form>
    <?php if ($this->getSearchString()): ?>
        <?= __('Current filter')?>: <?= $this->getSearchString()?>
        <a href="<?= $this->getFilterActionUrl()?>"><?= __('Reset') ?></a>
    <?php endif; ?>
    <table class="data table table-order-items history" id="my-orders-table">
        <thead>
        <tr>
            <th scope="col" class="col id">
                <a href="<?= $this->getSortLink('No.')?>">
                    <?= __('Shipment #') ?>
                    <?= $this->getSortIcon('No.') ?>
                </a>
            </th>
            <th scope="col" class="col date">
                <a href="<?= $this->getSortLink('Order Date')?>">
                    <?= __('Date') ?>
                    <?= $this->getSortIcon('Order Date') ?>
                </a>
            </th>
            <th scope="col" class="col status">
                <a href="<?= $this->getSortLink('Order No.')?>">
                    <?= __('From Order #') ?>
                    <?= $this->getSortIcon('Order No.') ?>
                </a>
            </th>
            <th scope="col" class="col shipping">
                <a href="<?= $this->getSortLink('Ship-to Name')?>">
                    <?= __('Ship To') ?>
                    <?= $this->getSortIcon('Ship-to Name') ?>
                </a>
            </th>
            <th scope="col" class="col total">
                <a href="<?= $this->getSortLink('Ship-to Address')?>">
                    <?= __('Address') ?>
                    <?= $this->getSortIcon('Ship-to Address') ?>
                </a>
            </th>
            <th scope="col" class="col total">
                <a href="<?= $this->getSortLink('Ship-to City')?>">
                    <?= __('City') ?>
                    <?= $this->getSortIcon('Ship-to City') ?>
                </a>
            </th>
            <th scope="col" class="col actions">&nbsp</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($shipments as $shipment): ?>
            <tr>
                <td data-th="Order #" class="col id"><?= $shipment["No."] ?></td>
                <td data-th="Date" class="col date"><?= date_format(date_create($shipment["Order Date"]), "d-m-Y") ?></td>
                <td data-th="Status #" class="col id"><?= $shipment["Order No."] ?></td>
                <td data-th="Ship To #" class="col id"><?= $shipment["Ship-to Name"]?></td>
                <td data-th="Ship To Address" class="col total"><?= $shipment["Ship-to Address"] ?></td>
                <td data-th="Ship To City" class="col total"><?= $shipment["Ship-to City"] ?></td>
                <td data-th="Actions" class="col actions">
                    <a href="<?= $this->getViewUrl($shipment["id"]) ?>" class="action view">
                        <span><?= __("View Shipment") ?></span>
                    </a>
                    <a href="<?= $shipment["PDFUrl"] ?>" class="action order" target="_blank">
                        <span>PDF</span>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <div class="message info empty"><span><?= __('No shipments found.') ?></span></div>
<?php endif; ?>
</div>

<?php if ($totalResults > $block->getPageSize()): ?>
    <div>
        <?= __('Page:') ?> <?= $block->getPage() ?> <?= __('of') ?> <?= $shipmentsResponse["totalPages"] ?>
    </div>
    <div>
        <?php if ($block->getPage() > 1): ?>
        <a href="<?= $this->getPreviousPageUrl($block->getPage()) ?>" class="action order"><?= __('Previous') ?></a>
        <?php endif; ?>
        <?php if ($block->getPage() > 1 && $block->getPage() < $shipmentsResponse["totalPages"]): ?>
            -
        <?php endif; ?>
        <?php if ($block->getPage() < $shipmentsResponse["totalPages"]): ?>
            <a href="<?= $this->getNextPageUrl($block->getPage()) ?>" class="action order"><?= __('Next') ?></a>
        <?php endif; ?>
    </div>
<?php endif; ?>


<!--

Below is a list of all sales shipment header fields / and sample data
All these fields are available in the API response, as well as any custom field added by customer/partner/other ISV

"id": "D4F66D86-6303-EB11-81A2-E016CCC29A3B",
"Sell-to Customer No.": "C00010",
"No.": "102215",
"Bill-to Customer No.": "C00010",
"Bill-to Name": "Signify HQ",
"Bill-to Name 2": "",
"Bill-to Address": "High Tech Campus 48",
"Bill-to Address 2": "",
"Bill-to City": "Eindhoven",
"Bill-to Contact": "Frits Philips",
"Your Reference": "",
"Ship-to Code": "",
"Ship-to Name": "Signify HQ",
"Ship-to Name 2": "",
"Ship-to Address": "High Tech Campus 48",
"Ship-to Address 2": "",
"Ship-to City": "Eindhoven",
"Ship-to Contact": "Frits Philips",
"Order Date": "2020-08-04",
"Posting Date": "2020-08-04",
"Shipment Date": "2020-08-04",
"Posting Description": "Order 101012",
"Payment Terms Code": "14 DAYS",
"Due Date": "2020-08-18",
"Payment Discount %": 0,
"Pmt. Discount Date": "2020-08-04",
"Shipment Method Code": "CFR",
"Location Code": "MAIN",
"Shortcut Dimension 1 Code": "",
"Shortcut Dimension 2 Code": "",
"Customer Posting Group": "EU",
"Currency Code": "EUR",
"Currency Factor": 1.548467017652524,
"Customer Price Group": "",
"Prices Including VAT": false,
"Invoice Disc. Code": "C00010",
"Customer Disc. Group": "",
"Language Code": "",
"Salesperson Code": "",
"Order No.": "101012",
"Comment": false,
"No. Printed": 0,
"On Hold": "",
"Applies-to Doc. Type": 0,
"Applies-to Doc. No.": "",
"Bal. Account No.": "",
"VAT Registration No.": "",
"Reason Code": "",
"Gen. Bus. Posting Group": "EU",
"EU 3-Party Trade": false,
"Transaction Type": "",
"Transport Method": "",
"VAT Country/Region Code": "NL",
"Sell-to Customer Name": "Signify HQ",
"Sell-to Customer Name 2": "",
"Sell-to Address": "High Tech Campus 48",
"Sell-to Address 2": "",
"Sell-to City": "Eindhoven",
"Sell-to Contact": "Frits Philips",
"Bill-to Post Code": "5656 AE",
"Bill-to County": "",
"Bill-to Country/Region Code": "NL",
"Sell-to Post Code": "5656 AE",
"Sell-to County": "",
"Sell-to Country/Region Code": "NL",
"Ship-to Post Code": "5656 AE",
"Ship-to County": "",
"Ship-to Country/Region Code": "NL",
"Bal. Account Type": 0,
"Exit Point": "",
"Correction": false,
"Document Date": "2020-08-04",
"External Document No.": "",
"Area": "",
"Transaction Specification": "",
"Payment Method Code": "BANK",
"Shipping Agent Code": "DHL",
"Package Tracking No.": "",
"No. Series": "S-SHPT",
"Order No. Series": "S-ORD",
"User ID": "USER",
"Source Code": "SALES",
"Tax Area Code": "",
"Tax Liable": false,
"VAT Bus. Posting Group": "EU",
"VAT Base Discount %": 0,
"Quote No.": "",
"Sell-to Phone No.": "+31 (0) 40 275 0000",
"Sell-to E-Mail": "frits@signify.com",
"Dimension Set ID": 0,
"Campaign No.": "",
"Sell-to Contact No.": "CT000024",
"Bill-to Contact No.": "CT000024",
"Opportunity No.": "",
"Responsibility Center": "",
"Requested Delivery Date": "2020-08-18",
"Promised Delivery Date": "0001-01-01",
"Shipping Agent Service Code": "STANDARD",
"Price Calculation Method": 1,
"Allow Line Disc.": true,
"IDYS E-Mail Type": "0",
"IDYS Cost Center": "",
"IDYS Account No.": "",
"NC365 Web Order": false,
"NC365 Staging Order No.": "",
"NC365 Store Code": "",
"PDFUrl": "https://commerce365.blob.core.windows.net/123/Shipment_102271_7BE21297-1234-4368-86AF-0563AFE5D3E5.pdf",
"Lines" [See below]:

-->

<!--

Below is a list of all sales shipment line fields / and sample data
Be aware that a specific customer might have additional custom fields on both header and line level

"Sell-to Customer No.": "C00010",
"Document No.": "102215",
"Line No.": 10000,
"Type": 2,
"No.": "1896-S",
"Location Code": "MAIN",
"Posting Group": "RESALE",
"Shipment Date": "2020-08-16",
"Description": "ATHENS Desk",
"Description 2": "",
"Unit of Measure": "Piece",
"Quantity": 2,
"Unit Price": 1005.574,
"Unit Cost (LCY)": 506.6,
"VAT %": 0,
"Line Discount %": 0,
"Allow Invoice Disc.": true,
"Gross Weight": 39.79,
"Net Weight": 34.6,
"Units per Parcel": 0,
"Unit Volume": 1.2,
"Appl.-to Item Entry": 0,
"Item Shpt. Entry No.": 658,
"Shortcut Dimension 1 Code": "",
"Shortcut Dimension 2 Code": "",
"Customer Price Group": "",
"Job No.": "",
"Work Type Code": "",
"Qty. Shipped Not Invoiced": 0,
"Quantity Invoiced": 2,
"Order No.": "101012",
"Order Line No.": 10000,
"Bill-to Customer No.": "C00010",
"Purchase Order No.": "",
"Purch. Order Line No.": 0,
"Drop Shipment": false,
"Gen. Bus. Posting Group": "EU",
"Gen. Prod. Posting Group": "RETAIL",
"VAT Calculation Type": 1,
"Transaction Type": "",
"Transport Method": "",
"Attached to Line No.": 0,
"Exit Point": "",
"Area": "",
"Transaction Specification": "",
"Tax Area Code": "",
"Tax Liable": false,
"Tax Group Code": "",
"VAT Bus. Posting Group": "EU",
"VAT Prod. Posting Group": "STANDARD",
"Currency Code": "EUR",
"Blanket Order No.": "",
"Blanket Order Line No.": 0,
"VAT Base Amount": 2011.15,
"Unit Cost": 784.453,
"IC Partner Ref. Type": 0,
"IC Partner Reference": "",
"Posting Date": "2020-08-04",
"Dimension Set ID": 0,
"Authorized for Credit Card": false,
"Job Task No.": "",
"Job Contract Entry No.": 0,
"Variant Code": "",
"Bin Code": "",
"Qty. per Unit of Measure": 1,
"Unit of Measure Code": "PCS",
"Quantity (Base)": 2,
"Qty. Invoiced (Base)": 2,
"FA Posting Date": "0001-01-01",
"Depreciation Book Code": "",
"Depr. until FA Posting Date": false,
"Duplicate in Depreciation Book": "",
"Use Duplication List": false,
"Responsibility Center": "",
"Cross-Reference No.": "",
"Unit of Measure (Cross Ref.)": "",
"Cross-Reference Type": 0,
"Cross-Reference Type No.": "",
"Item Category Code": "TABLE",
"Nonstock": false,
"Purchasing Code": "",
"Requested Delivery Date": "2020-08-18",
"Promised Delivery Date": "0001-01-01",
"Planned Delivery Date": "2020-08-18",
"Planned Shipment Date": "2020-08-16",
"Appl.-from Item Entry": 0,
"Item Charge Base Amount": 2011.15,
"Correction": false,
"Return Reason Code": "",
"Price Calculation Method": 1,
"Allow Line Disc.": true,
"Customer Disc. Group": ""

-->
