<?php declare(strict_types=1);

use Commerce365\Quotes\Block\ShipmentDetails;
use Magento\Framework\Escaper;

/** @var ShipmentDetails  $block */
/** @var Escaper $escaper */

$shipment = $block->getShipment();
$shipmentLines = $shipment["Lines"];
?>

<div class="md:flex md:justify-between items-center mb-3">
    <div class="lg:flex items-center text-center md:text-left">
        <div class="lg:inline-block">
            <h2 class="text-2xl">
                <span><?= $escaper->escapeHtml(__('Shipment # %1', $shipment["No."])) ?></span>
            </h2>
            <div class="order-date">
                <span class="label"><?= $escaper->escapeHtml(__('Shipment Date:')) ?></span>
                <date><?= date_format(date_create($shipment["Document Date"]), "d-m-Y") ?></date>
            </div>
        </div>
    </div>
    <div class="actions">
        <a href="<?= $shipment["PDFUrl"] ?>" class="btn btn-secondary mb-4 order" style="justify-content: center;"
            target="_blank">
            <?= $escaper-> escapeUrl(__('Download PDF')) ?>
        </a>
    </div>
</div>

<div class="order-details-items ordered">
    <div class="-mx-4">
        <ul class="items order-links">
            <li class="nav item current">
                <strong><?= $escaper->escapeHtml(__('Items Shipped')) ?></strong>
            </li>
        </ul>
    </div>
    <div class="p4 card">
        <div class="table-wrapper order-items">
            <table id="my-orders-table" class="w-full">
                <caption class="order-title sr-only"><?= $escaper->escapeHtml(__('Items Shipped')) ?></caption>
                <thead>
                    <tr>
                        <th class="col name p-2 text-left"><?= __('Product Name') ?></th>
                        <th class="col sku p-2 text-left"><?= __('SKU') ?></th>
                        <th class="col qty p-2 text-left"><?= __('Qty') ?></th>
                    </tr>
                </thead>

                <?php foreach ($shipmentLines as $shipmentLine): ?>
                <?php
                    $itemNo = '';
                    if ((int)$shipmentLine["Type"] === 2) {
                        $itemNo = $shipmentLine["No."];
                    }
                ?>
                <tbody>
                    <tr id="order-item-row-1">
                        <td class="col name p-2" data-th="Product Name">
                            <strong class="product name product-item-name"><?= $shipmentLine["Description"]?></strong>
                        </td>
                        <td class="col sku p-2" data-th="SKU"><?= $itemNo ?></td>
                        <td class="col qty p-2" data-th="Qty">
                            <ul class="items-qty">
                                <li class="item">
                                    <span class="content"><?= $shipmentLine["Quantity"] ?></span>
                                </li>
                            </ul>
                        </td>
                    </tr>
                </tbody>
                <?php endforeach; ?>
            </table>
        </div>
        <div class="actions-toolbar">
            <div class="secondary">
                <a class="action back" href="/orders/orderlist/">
                    <span><?= $escaper->escapeHtml(__('Back to My Shipment')) ?></span>
                </a>
            </div>
        </div>
    </div>
</div>
<div class="mt-8">
    <div class="block-title mb-2">
        <strong><?= $escaper->escapeHtml(__('Shipment Information')) ?></strong>
    </div>
    <div class="p-4 card">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div class="order-shipping-address">
                <strong class="block text-lg mb-2"><?= $escaper->escapeHtml(__('Shipping Address')) ?></strong>
                <div class="box-content">
                    <address class="not-italic"><?= $shipment["Ship-to Name"]; ?><br />
                        <?= $shipment["Ship-to Address"]; ?><br />
                        <?= $shipment["Ship-to City"]; ?>, <?= $shipment["Ship-to Post Code"]; ?><br />
                        <?= $shipment["Ship-to Country/Region Code"]; ?><br />
                    </address>
                </div>
            </div>
            <div class="order-shipping-method">
                <strong class="block text-lg mb-2"><?= $escaper->escapeHtml(__('Shipping Method')) ?></strong>
                <div class="box-content">
                    <div><?= $shipment["Shipment Method Code"]; ?></div>
                </div>
            </div>
            <div class="order-billing-address">
                <strong class="block text-lg mb-2"><?= $escaper->escapeHtml(__('Billing Address')) ?></strong>
                <div class="box-content">
                    <address class="not-italic"><?= $shipment["Bill-to Name"]; ?><br />
                        <?= $shipment["Bill-to Address"]; ?><br />
                        <?= $shipment["Bill-to City"]; ?>, <?= $shipment["Bill-to Post Code"]; ?><br />
                        <?= $shipment["Bill-to Country/Region Code"]; ?><br />
                    </address>
                </div>
            </div>
            <div class="box box-order-billing-method">
                <strong class="block text-lg mb-2"><?= $escaper->escapeHtml(__('Payment Method')) ?></strong>
                <div class="box-content">
                    <dl class="payment-method checkmemo">
                        <?php echo $shipment["Payment Method Code"]; ?>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>